common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin, google_login, create_lead_from_site,
    activate_user, resend_activation_link
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),
    path('google/login/', google_login, name="google_login"),
    path('create-lead-from-site/', create_lead_from_site,
         name='create_lead_from_site'),

    # user activate link
    path('activate-user/<uidb64>/<token>/<activation_key>/', activate_user, name='activate_user'),
    path('resend_activation_link/<userId>/', resend_activation_link, name='resend_activation_link'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500
from django.contrib import admin

app_name = 'crm'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    # path('marketing/', include('marketing.urls', namespace="marketing")),
    # path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    # path('opportunities/',
        #  include('opportunity.urls', namespace="opportunities")),
    # path('cases/', include('cases.urls', namespace="cases")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    # path('invoices/', include('invoices.urls', namespace="invoices")),
    # path('events/', include('events.urls', namespace="events")),
    path('teams/', include('teams.urls', namespace="teams")),
    # path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout")

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

leads/urls.py
from django.urls import path
from leads.views import (
    LeadListView, create_lead, LeadDetailView,
    update_lead, DeleteLeadView, convert_lead,
    GetLeadsView, AddCommentView, UpdateCommentView, DeleteCommentView,
    AddAttachmentsView, DeleteAttachmentsView, create_lead_from_site,
    update_lead_tags, remove_lead_tag, upload_lead_csv_file, sample_lead_file,
    lead_list_view, get_teams_and_users
)


app_name = 'leads'


urlpatterns = [
#     path('', LeadListView.as_view(), name='list'),
    path('', lead_list_view, name='list'),
    path('create/', create_lead, name='add_lead'),
    # create_lead_from_site
    path('create/from-site/', create_lead_from_site,
         name="create_lead_from_site"),
    path('<int:pk>/view/', LeadDetailView.as_view(), name="view_lead"),
    path('<int:pk>/edit/', update_lead, name="edit_lead"),
    path('<int:pk>/delete/', DeleteLeadView.as_view(), name="remove_lead"),
    path('<int:pk>/convert/', convert_lead, name="leads_convert"),

    path('get/list/', GetLeadsView.as_view(), name="get_lead"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/',
         DeleteCommentView.as_view(), name="remove_comment"),

    path('attachment/add/',
         AddAttachmentsView.as_view(), name="add_attachment"),
    path('attachment/remove/', DeleteAttachmentsView.as_view(),
         name="remove_attachment"),
    path('update_lead_tags/<pk>/', update_lead_tags, name="update_lead_tags"),
    path('remove_lead_tag/', remove_lead_tag, name="remove_lead_tag"),
    path('upload_lead_csv_file/', upload_lead_csv_file, name="upload_lead_csv_file"),
    path('sample_lead_file/', sample_lead_file, name="sample_lead_file"),
    path('get_teams_and_users/', get_teams_and_users, name="get_teams_and_users")
]

common/forms.py
import re
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm
from common.models import Address, User, Document, Comment, APISettings
from django.contrib.auth import password_validation
from teams.models import Teams


class BillingAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ('address_line', 'street', 'city',
                  'state', 'postcode', 'country')

    def __init__(self, *args, **kwargs):
        account_view = kwargs.pop('account', False)

        super(BillingAddressForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['address_line'].widget.attrs.update({
            'placeholder': 'Address Line'})
        self.fields['street'].widget.attrs.update({
            'placeholder': 'Street'})
        self.fields['city'].widget.attrs.update({
            'placeholder': 'City'})
        self.fields['state'].widget.attrs.update({
            'placeholder': 'State'})
        self.fields['postcode'].widget.attrs.update({
            'placeholder': 'Postcode'})
        self.fields["country"].choices = [
            ("", "--Country--"), ] + list(self.fields["country"].choices)[1:]

        if account_view:
            self.fields['address_line'].required = True
            self.fields['street'].required = True
            self.fields['city'].required = True
            self.fields['state'].required = True
            self.fields['postcode'].required = True
            self.fields['country'].required = True


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('address_line', 'street', 'city',
                  'state', 'postcode', 'country')

    def __init__(self, *args, **kwargs):
        super(ShippingAddressForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['address_line'].widget.attrs.update({
            'placeholder': 'Address Line'})
        self.fields['street'].widget.attrs.update({
            'placeholder': 'Street'})
        self.fields['city'].widget.attrs.update({
            'placeholder': 'City'})
        self.fields['state'].widget.attrs.update({
            'placeholder': 'State'})
        self.fields['postcode'].widget.attrs.update({
            'placeholder': 'Postcode'})
        self.fields["country"].choices = [
            ("", "--Country--"), ] + list(self.fields["country"].choices)[1:]


class UserForm(forms.ModelForm):

    password = forms.CharField(max_length=100, required=False)
    # sales = forms.BooleanField(required=False)
    # marketing = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name',
                  'username', 'role', 'profile_pic',
                  'has_sales_access', 'has_marketing_access']

    def __init__(self, *args, **kwargs):
        self.request_user = kwargs.pop('request_user', None)
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        if not self.instance.pk:
            self.fields['password'].required = True

        # self.fields['password'].required = True

    # def __init__(self, args: object, kwargs: object) -> object:
    #     super(UserForm, self).__init__(*args, **kwargs)
    #
    #     self.fields['first_name'].required = True
    #     self.fields['username'].required = True
    #     self.fields['email'].required = True
    #
        # if not self.instance.pk:
        #     self.fields['password'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'Password must be at least 4 characters long!')
        return password

    def clean_has_sales_access(self):
        sales = self.cleaned_data.get('has_sales_access', False)
        user_role = self.cleaned_data.get('role')
        if user_role == 'ADMIN':
            is_admin = True
        else:
            is_admin = False
        if self.request_user.role == 'ADMIN' or self.request_user.is_superuser:
            if not is_admin:
                marketing = self.data.get('has_marketing_access', False)
                if not sales and not marketing:
                    raise forms.ValidationError('Select atleast one option.')
            # if not (self.instance.role == 'ADMIN' or self.instance.is_superuser):
            #     marketing = self.data.get('has_marketing_access', False)
            #     if not sales and not marketing:
            #         raise forms.ValidationError('Select atleast one option.')
        if self.request_user.role == 'USER':
            sales = self.instance.has_sales_access
        return sales

    def clean_has_marketing_access(self):
        marketing = self.cleaned_data.get('has_marketing_access', False)
        if self.request_user.role == 'USER':
            marketing = self.instance.has_marketing_access
        return marketing

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance.id:
            if self.instance.email != email:
                if not User.objects.filter(
                        email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
                raise forms.ValidationError('Email already exists')
            else:
                return self.cleaned_data.get("email")
        else:
            if not User.objects.filter(
                    email=self.cleaned_data.get("email")).exists():
                return self.cleaned_data.get("email")
            raise forms.ValidationError('User already exists with this email')


class LoginForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'Password must be at least 4 characters long!')
        return password

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(username=email, password=password)
            if self.user:
                if not self.user.is_active:
                    pass
                    # raise forms.ValidationError("User is Inactive")
            else:
                pass
                # raise forms.ValidationError("Invalid email and password")
        return self.cleaned_data


class ChangePasswordForm(forms.Form):
    # CurrentPassword = forms.CharField(max_length=100)
    Newpassword = forms.CharField(max_length=100)
    confirm = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_confirm(self):
        # if len(self.data.get('confirm')) < 4:
        #     raise forms.ValidationError(
        #         'Password must be at least 4 characters long!')
        if self.data.get('confirm') != self.cleaned_data.get('Newpassword'):
            raise forms.ValidationError(
                'Confirm password do not match with new password')
        password_validation.validate_password(
            self.cleaned_data.get('Newpassword'), user=self.user)
        return self.data.get('confirm')


class PasswordResetEmailForm(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email__iexact=email,
                                   is_active=True).exists():
            raise forms.ValidationError("User doesn't exist with this Email")
        return email


class DocumentForm(forms.ModelForm):
    teams_queryset = []
    teams = forms.MultipleChoiceField(choices=teams_queryset)

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.get('instance', None)
        users = kwargs.pop('users', [])
        super(DocumentForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}

        self.fields['status'].choices = [
            (each[0], each[1]) for each in Document.DOCUMENT_STATUS_CHOICE]
        self.fields['status'].required = False
        self.fields['title'].required = True
        if users:
            self.fields['shared_to'].queryset = users
        self.fields['shared_to'].required = False
        self.fields["teams"].choices = [(team.get('id'), team.get('name')) for team in Teams.objects.all().values('id', 'name')]
        self.fields["teams"].required = False

    class Meta:
        model = Document
        fields = ['title', 'document_file', 'status', 'shared_to']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not self.instance.id:
            if Document.objects.filter(title=title).exists():
                raise forms.ValidationError(
                    'Document with this Title already exists')
                return title
        if Document.objects.filter(title=title).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(
                'Document with this Title already exists')
            return title
        return title


class UserCommentForm(forms.ModelForm):

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

    {% compress css %}
    <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %} {% endblock %}
  </head>
  <body class="main_body_bg_color">
    <div class="wrapper">
      <!-- header starts here -->
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">

          <a class="navbar-brand" href="{% url 'common:home' %}">Django CRM</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" id="dashboard" href="{% url 'common:home' %}">Dashboard</a></li>
              {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:users_list' %}">Users</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" id="accounts" href="">Accounts</a></li>
              <li class="nav-item"><a class="nav-link" id="contacts" href="{% url 'contacts:list' %}">Contacts</a></li>
              <li class="nav-item"><a class="nav-link" id="leads" href="{% url 'leads:list' %}">Leads</a></li>
              <li class="nav-item"><a class="nav-link" id="opportunities"href="=">Opportunities</a></li>
              <li class="nav-item"><a class="nav-link" id="cases" href="">Cases</a></li>
              <li class="nav-item"><a class="nav-link" id="documents" href="{% url 'common:doc_list' %}">Documents</a></li>
              {% if request.user.role == "ADMIN" or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:api_settings' %}">Settings</a></li>
              {% endif %}
            </ul>
            <ul class="navbar-nav navbar-right my-2 my-lg-0">
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false" >
                {% if not request.user.profile_pic %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                {% else %}
                {% thumbnail request.user.profile_pic "25x25" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% endif %}
                <b class="caret"></b></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  {% if request.user.email != "admin@micropyramid.com" %}
                  <a class="dropdown-item" href="/change-password/"><i class="fas fa-key"></i> Change Password</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'common:profile' %}"><i class="fas fa-user"></i> Profile</a>
                  <a class="dropdown-item" href="{% url 'common:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </div>
              </li>
            </ul>
          </div>
          {% endif %}
        </nav>
      </header>
      <!-- header ends here -->
      <!-- main_container starts here -->
      <div id="mainbody" class="main_container" style="padding-top:65px;">
        <!-- breadcrumb starts here -->
        {% block breadcrumb %}
        {% endblock %}
        <!-- breadcrumb ends here -->
        {% block content %}
        {% endblock %}
      </div>
      <!-- main_container ends here -->
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment-with-locales.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    {% block js_block %}
    {% endblock js_block %}
    <script type="text/javascript">
      $(document).ready(function(){
          word = window.location.pathname.split('/')[1]
          if(word == ""){
            $("#dashboard").addClass('active')
          }
          else{
            $('#' + word).addClass('active')
          }
      });
    </script>
  </body>
</html>

templates/login.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Django CRM</title>
  <!-- Bootstrap core CSS -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
  <!-- Custom styling plus plugins -->
  {% compress css %}
  <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
  {% endcompress %}
  {% block extralinks %}{% endblock %}
</head>

<body class="login_register_body">
  {% if messages %}
  <ul style="font-size: 1.5em;" class="text-center mt-5">
    {% for message in messages %}
    {{ message|safe }}
    {% endfor %}
  </ul>
  {% endif %}
  <div class="container">
    <div class="row marl justify-content-center login_row">
      <div class="col-md-6 col-lg-6 col-xl-4">
        <div class="login_block">
          <div class="login_form_block">
            <div class="welcome">Django CRM</div>
            <form method="POST" action="">
              <div class="form-group">
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                <span class="error">{{form.email.errors}}</span>
              </div>
              <div class="form-group">
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                  name="password">
                <span class="error">{{form.password.errors}}</span>
              </div>
              <div class="forgot">Forgot Password <a href="{% url "common:password_reset" %}">Click Here?</a></div>
              {% if error %}
              <p class="error">{{ message }}</p>
              {% endif %}
              <button type="submit" class="btn btn-danger">Login</button>
              &nbsp;
              {% if ENABLE_GOOGLE_LOGIN and GP_CLIENT_SECRET and GP_CLIENT_ID %}
              <a href="{% url 'common:google_login' %}" class="btn btn-primary">Google Login</a>
              {% endif %}
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

templates/new_user.html
hello {{user.email}},

<p>Your account has been successfully created in Django CRM by {{created_by.email}}</p>

templates/profile.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content%}

<!-- OPPORTUNITY VIEW STARTS -->
<div class="main_container" id="maincontainer">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body" id="datashow">
          <div class="panel-heading card-title view-pad text-center">
            <h5>
              Profile
              <!-- <span class="float-right" style="margin-top: 0px">
                  <div class="dropdown buttons_row">
                    <button class="btn btn-primary dropdown-toggle save" type="button" data-toggle="dropdown">Actions
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#" >Edit</a></li>
                      <li class="delete_contact"><a href="#" id="remove_contact">Remove</a></li>
                    </ul>
                  </div>
                </span> -->
            </h5>
            <a href="{% url 'common:edit_user' user_obj.id %}" class="btn btn-success edit">Edit</a>
          </div>
          <div class="row marl no-gutters">
            <div class="col-md-8">
              {% if user_obj.first_name %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_name" data-name="name">Name</label>
                  <div class="contact_field" id="contact_name" data-name="name">{{ user_obj.first_name }}
                    {{ user_obj.last_name }}</div>
                </div>
              </div>
              {% endif %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_contact_account" data-name="name">UserName</label>
                  <div class="contact_field" id="contact_account" data-name="name">{{ user_obj.username }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_email" data-name="name">Email</label>
                  <div class="contact_field" id="contact_email" data-name="name">{{ user_obj.email }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_email" data-name="name">Permissions</label>
                  <div class="contact_field" id="contact_email" data-name="name">
                    {% if user_obj.is_superuser or user_obj.role == 'ADMIN' %}
                    Sales and Marketing
                    {% else %}
                    {% if user_obj.has_sales_access and user_obj.has_marketing_access %}
                    Sales and Marketing
                    {% elif user_obj.has_sales_access and not user_obj.has_marketing_access %}
                    Sales
                    {% elif not user_obj.has_sales_access and user_obj.has_marketing_access %}
                    Marketing
                    {% else %}
                    {{''}}
                    {% endif %}
                    {% endif %}

                  </div>
                </div>
              </div>
              {% with teams=user_obj.user_teams.all %}
              {% if teams %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="acc_field_label" for="id_industry" data-name="name">Teams</label>
                  {% for team in teams %}
                  <div class="account_field" id="account_industry" data-name="name">{{ team }}</div>
                  {% endfor %}
                </div>
              </div>
              {% endif %}
              {% endwith %}
            </div>
            <div class="col-md-4">
              <div class="profile_pic">
                {% if user_obj.profile_pic %}
                {% thumbnail request.user.profile_pic "125x125" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% else %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic" />
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}

templates/registration.html
{% extends 'sales/base.html' %}
{% block content %}
<h1>Registration</h1>
<form method="POST" class="user-form">
  {{ reg_form.as_p }}
  <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}